#MySQL is a database used by wordpress. Wordpress creates its html files dynamically, making queries to mysql database and based on data creates html file.
#Phpmyadmin can be used to manage the mysql database through your browser, easy to use interface.

FROM alpine:latest

MAINTAINER Henry Buisseret <hbuisser@student.s19.be>

RUN apk update && apk add mysql mysql-client


EXPOSE	3306