apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
# Part for the pods, with also metadata and spec
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        env:
        - name: SSH_USER
          value: admin
        - name: SSH_PASSWORD
          value: admin


---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
# NodePort type expose the container to the outside world 
  type: LoadBalancer
# link the deployemnt with the pods
  selector:
    app: nginx
  ports:
    - port: 80
# the service target port match the container port in the deployemnt
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
    - port: 22
      targetPort: 22
      name: ssh
      protocol: TCP
  
