# https://medium.com/@taweesoft/chapter-1-how-to-easily-deploy-your-web-on-kubernetes-83209a8618be

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 5050
          name: http
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  #namespace: metallb-system # Match with namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  ports:
  - port: 5050 # Port that publicly exposed to internet
    targetPort: 5050 # Match with MARK C.1
    protocol: TCP
  selector:
    app: wordpress # Match with MARK C
    tier: frontend