apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage
  namespace: metallb-system # Match with namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi